name: "Run Tests"

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job automatically triggered by a ${{ github.event_name }} event"
          echo "Job running on a ${{ runner.os }} server"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

