name: "tests"

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job automatically triggered by a ${{ github.event_name }} event"
          echo "Job running on a ${{ runner.os }} server"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools six wheel
          python -m pip install -r requirements.txt
      - name: Run Tests
        run: scripts/run-tests.sh
      - if: ${{ success() }}
        run: echo "Tests successful!"

